import type {
  DashboardLead,
  PricingProfile,
  RooferProfile,
} from "@/lib/types";

/** Demo roofer whose dashboard we're viewing. */
export const rooferProfile: RooferProfile = {
  name: "Summit Roofing Co.",
  slug: "quoter-landing-demo",
  base: "Reading, RG1 2AB",
  plan: "Quoter Pro",
  contactEmail: "hello@summitroofing.co.uk",
};

/**
 * Mock leads. Shapes mirror the persisted `leads` table; accessScore and
 * distanceMiles are mock-only (see types.ts).
 *
 * Timestamps are derived from a FIXED reference instant (not `Date.now()`), so
 * the module evaluates to identical values on the server and the client. A
 * now-based value here evaluates at server start and again at client load —
 * different instants — which breaks React hydration on the rendered times.
 */
const DEMO_NOW = Date.parse("2026-07-20T15:00:00Z");
const hoursAgo = (h: number) => new Date(DEMO_NOW - h * 3600_000).toISOString();

export const mockLeads: DashboardLead[] = [
  {
    id: "ld_1001",
    status: "new",
    leadType: "quote",
    jobType: "full_replacement",
    contactName: "James Whitmore",
    contactPhone: "07700 900123",
    contactEmail: "j.whitmore@gmail.com",
    addressFormatted: "14 Kendrick Road, Reading",
    addressPostcode: "RG1 5DL",
    quoteMinExVat: 8200,
    quoteMaxExVat: 11400,
    accessScore: "moderate",
    distanceMiles: 2.3,
    receivedAt: hoursAgo(1),
  },
  {
    id: "ld_1002",
    status: "new",
    leadType: "quote",
    jobType: "tile_or_slate_repair",
    contactName: "Priya Nair",
    contactPhone: "07700 900456",
    contactEmail: "priya.nair@outlook.com",
    addressFormatted: "3 Wilson Road, Reading",
    addressPostcode: "RG30 2RJ",
    quoteMinExVat: 640,
    quoteMaxExVat: 980,
    accessScore: "easy",
    distanceMiles: 3.8,
    receivedAt: hoursAgo(4),
  },
  {
    id: "ld_1003",
    status: "contacted",
    leadType: "quote",
    jobType: "flat_roof_replacement",
    contactName: "Daniel Osei",
    contactPhone: "07700 900789",
    contactEmail: "d.osei@icloud.com",
    addressFormatted: "27 Alexandra Road, Wokingham",
    addressPostcode: "RG40 1PD",
    quoteMinExVat: 3100,
    quoteMaxExVat: 4450,
    accessScore: "moderate",
    distanceMiles: 6.1,
    receivedAt: hoursAgo(9),
  },
  {
    id: "ld_1004",
    status: "contacted",
    leadType: "manual_consultation",
    jobType: "leak_investigation",
    contactName: "Sarah Bexley",
    contactPhone: "07700 900234",
    contactEmail: null,
    addressFormatted: "82 Southampton Street, Reading",
    addressPostcode: "RG1 2QU",
    quoteMinExVat: null,
    quoteMaxExVat: null,
    accessScore: "difficult",
    distanceMiles: 1.4,
    receivedAt: hoursAgo(20),
  },
  {
    id: "ld_1005",
    status: "won",
    leadType: "quote",
    jobType: "full_replacement",
    contactName: "Michael Trent",
    contactPhone: "07700 900567",
    contactEmail: "mtrent@btinternet.com",
    addressFormatted: "5 Bath Road, Calcot",
    addressPostcode: "RG31 7QN",
    quoteMinExVat: 9800,
    quoteMaxExVat: 13600,
    accessScore: "moderate",
    distanceMiles: 4.9,
    receivedAt: hoursAgo(28),
  },
  {
    id: "ld_1006",
    status: "won",
    leadType: "quote",
    jobType: "gutters_fascias_soffits",
    contactName: "Elaine Forsythe",
    contactPhone: "07700 900890",
    contactEmail: "elaine.f@gmail.com",
    addressFormatted: "19 Hemdean Road, Caversham",
    addressPostcode: "RG4 7SS",
    quoteMinExVat: 1450,
    quoteMaxExVat: 2100,
    accessScore: "easy",
    distanceMiles: 3.2,
    receivedAt: hoursAgo(35),
  },
  {
    id: "ld_1007",
    status: "new",
    leadType: "quote",
    jobType: "full_replacement",
    contactName: "Owen Prichard",
    contactPhone: "07700 900321",
    contactEmail: "owen.prichard@gmail.com",
    addressFormatted: "44 Northumberland Avenue, Reading",
    addressPostcode: "RG2 7PW",
    quoteMinExVat: 7600,
    quoteMaxExVat: 10200,
    accessScore: "difficult",
    distanceMiles: 2.8,
    receivedAt: hoursAgo(48),
  },
  {
    id: "ld_1008",
    status: "lost",
    leadType: "quote",
    jobType: "flat_roof_replacement",
    contactName: "Hannah Yeung",
    contactPhone: "07700 900654",
    contactEmail: "h.yeung@outlook.com",
    addressFormatted: "9 Cressingham Road, Reading",
    addressPostcode: "RG2 7RT",
    quoteMinExVat: 2650,
    quoteMaxExVat: 3900,
    accessScore: "moderate",
    distanceMiles: 5.5,
    receivedAt: hoursAgo(60),
  },
  {
    id: "ld_1009",
    status: "contacted",
    leadType: "quote",
    jobType: "tile_or_slate_repair",
    contactName: "Robert Adeyemi",
    contactPhone: "07700 900987",
    contactEmail: "r.adeyemi@icloud.com",
    addressFormatted: "31 Basingstoke Road, Reading",
    addressPostcode: "RG2 0EN",
    quoteMinExVat: 880,
    quoteMaxExVat: 1350,
    accessScore: "easy",
    distanceMiles: 3.0,
    receivedAt: hoursAgo(72),
  },
  {
    id: "ld_1010",
    status: "new",
    leadType: "quote",
    jobType: "other",
    contactName: "Claire Donovan",
    contactPhone: "07700 900147",
    contactEmail: "claire.donovan@gmail.com",
    addressFormatted: "6 Prospect Street, Caversham",
    addressPostcode: "RG4 8JB",
    quoteMinExVat: 1900,
    quoteMaxExVat: 2800,
    accessScore: "moderate",
    distanceMiles: 3.6,
    receivedAt: hoursAgo(90),
  },
  {
    id: "ld_1011",
    status: "won",
    leadType: "quote",
    jobType: "leak_investigation",
    contactName: "Thomas Reeves",
    contactPhone: "07700 900258",
    contactEmail: "treeves@btinternet.com",
    addressFormatted: "52 Erleigh Road, Reading",
    addressPostcode: "RG1 5NA",
    quoteMinExVat: 320,
    quoteMaxExVat: 480,
    accessScore: "easy",
    distanceMiles: 1.9,
    receivedAt: hoursAgo(120),
  },
  {
    id: "ld_1012",
    status: "lost",
    leadType: "quote",
    jobType: "full_replacement",
    contactName: "Amara Okonkwo",
    contactPhone: "07700 900369",
    contactEmail: "amara.o@outlook.com",
    addressFormatted: "11 Tilehurst Road, Reading",
    addressPostcode: "RG1 7TT",
    quoteMinExVat: 8900,
    quoteMaxExVat: 12300,
    accessScore: "difficult",
    distanceMiles: 4.1,
    receivedAt: hoursAgo(150),
    archived: true,
  },
];

/** Mock pricing profile shown on the Account page. */
export const mockPricing: PricingProfile = {
  materials: [
    { key: "concrete_tile", label: "Concrete tile", unit: "£/m²", rate: 48 },
    { key: "clay_tile", label: "Clay tile", unit: "£/m²", rate: 72 },
    { key: "natural_slate", label: "Natural slate", unit: "£/m²", rate: 95 },
    { key: "epdm", label: "EPDM rubber (flat)", unit: "£/m²", rate: 60 },
    { key: "grp", label: "GRP fibreglass (flat)", unit: "£/m²", rate: 85 },
    { key: "felt", label: "Built-up felt (flat)", unit: "£/m²", rate: 45 },
  ],
  labourPerDay: 220,
  minimumCallout: 180,
  skipHire: 260,
  scaffoldPerWeek: 550,
  vatRegistered: true,
};
